[package]
name = "ducci"
version = "1.2.0"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]
description = "A library for creating Ducci sequences from n-tuples"
repository = "https://github.com/sphinxc0re/ducci"
readme = "README.md"
license = "GPL-3.0"
